name: Django Tests
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Setup a virtual environment
        run:
          python3 -m venv env
          . env/bin/activate
      - name: Install dependencies
        run:
          pip3 install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip3 install flake8
          flake8
      - name: Coverage report
        run: |
          pip3 install coverage
          coverage run manage.py test
          coverage report
      - name: Django Testing
        run: |
          python3 manage.py test

        